services:
  webui:
    image: khairul169/garage-webui:1.1.0
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://webui-gateway:3903"
      S3_ENDPOINT_URL: "http://webui-gateway:3900"
      API_ADMIN_KEY: ${GARAGE_ADMIN_TOKEN}
    depends_on:
      - webui-gateway
    networks:
      garage-net:
      default:

  webui-gateway:
    image: dxflrs/garage:v2.1.0
    container_name: webui-gateway
    volumes:
      - ./config/webui-gateway.toml:/etc/garage.toml:ro
      - webui-gateway-meta:/var/lib/garage/meta
      - webui-gateway-data:/var/lib/garage/data
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_ADMIN_TOKEN: ${GARAGE_ADMIN_TOKEN}
    networks:
      garage-net:
        ipv6_address: 2001:db8::43:2

  # Each storage node or gateway could run on a different physical host or VM.
  # The important part is that they can reach each other via their IPv6 addresses.

  regular-gateway:
    image: dxflrs/garage:v2.1.0
    container_name: regular-gateway
    volumes:
      - ./config/regular-gateway.toml:/etc/garage.toml:ro
      - regular-gateway-meta:/var/lib/garage/meta
      - regular-gateway-data:/var/lib/garage/data
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
    networks:
      garage-net:
        ipv6_address: 2001:db8::43:3

  storage-node1:
    image: dxflrs/garage:v2.1.0
    container_name: storage-node1
    volumes:
      - ./config/storage-node.toml:/etc/garage.toml:ro
      - storage-node1-meta:/var/lib/garage/meta
      - storage-node1-data:/var/lib/garage/data
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_METRICS_TOKEN: ${GARAGE_METRICS_TOKEN}
    networks:
      garage-net:
        ipv6_address: 2001:db8::42:1

  storage-node2:
    image: dxflrs/garage:v2.1.0
    container_name: storage-node2
    volumes:
      - ./config/storage-node.toml:/etc/garage.toml:ro
      - storage-node2-meta:/var/lib/garage/meta
      - storage-node2-data:/var/lib/garage/data
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_METRICS_TOKEN: ${GARAGE_METRICS_TOKEN}
    networks:
      garage-net:
        ipv6_address: 2001:db8::42:2

  storage-node3:
    image: dxflrs/garage:v2.1.0
    container_name: storage-node3
    volumes:
      - ./config/storage-node.toml:/etc/garage.toml:ro
      - storage-node3-meta:/var/lib/garage/meta
      - storage-node3-data:/var/lib/garage/data
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_METRICS_TOKEN: ${GARAGE_METRICS_TOKEN}
    networks:
      garage-net:
        ipv6_address: 2001:db8::42:3

  storage-node4:
    image: dxflrs/garage:v2.1.0
    container_name: storage-node4
    volumes:
      - ./config/storage-node.toml:/etc/garage.toml:ro
      - storage-node4-meta:/var/lib/garage/meta
      - storage-node4-data:/var/lib/garage/data
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_METRICS_TOKEN: ${GARAGE_METRICS_TOKEN}
    networks:
      garage-net:
        ipv6_address: 2001:db8::42:4

networks:
  garage-net:
    driver: bridge
    enable_ipv4: false
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:db8::/64

volumes:
  webui-gateway-data:
  webui-gateway-meta:
  regular-gateway-data:
  regular-gateway-meta:
  storage-node1-data:
  storage-node1-meta:
  storage-node2-data:
  storage-node2-meta:
  storage-node3-data:
  storage-node3-meta:
  storage-node4-data:
  storage-node4-meta:
