metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 3

compression_level = 2

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "[2001:db8::42:3]:3901"

[s3_api]
s3_region = "garage"
# api_bind_addr = "[::]:3900"
# root_domain = ".s3.emrio.fr"

[admin]
api_bind_addr = "[::]:3903"
